# Generated by Django 4.2.4 on 2023-08-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_testquestion_userresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.candidate')),
            ],
        ),
    ]
