# Generated by Django 4.2.4 on 2023-08-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_testtimer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_smooth', models.BooleanField()),
                ('instructions_clear', models.BooleanField()),
                ('issues_with_saving', models.BooleanField()),
                ('test_difficulty', models.CharField(max_length=50)),
                ('questions_clear', models.BooleanField()),
                ('poorly_worded_questions', models.TextField()),
                ('enough_time', models.BooleanField()),
                ('unexpected_issues', models.TextField()),
                ('ui_intuitive', models.BooleanField()),
                ('improvement_suggestions', models.TextField()),
                ('test_format_appropriate', models.BooleanField()),
                ('preferred_question_types', models.TextField()),
                ('felt_anxious', models.BooleanField()),
                ('reason_for_anxiety', models.TextField()),
                ('sequence_logical', models.BooleanField()),
                ('overall_experience', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.candidate')),
            ],
        ),
    ]
